# azure-pipelines.yml (in GitHub/Test)
trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self   # this is your GitHub/Test repo

  - bash: |
      set -e

      echo "🔐 Cloning private Azure DevOps repo..."
      # Use the env var $AZDO_PAT, not $(AZDO_PAT), inside the shell
      git clone https://$AZDO_PAT@dev.azure.com/zalaris/Zalaris%20IT%20Infrastructure/_git/Zalaris%20IT%20Infra%20-%20Netbox azureRepo

      echo "✅ Clone complete: $(ls -1 azureRepo | sed -e 's/^/   /')"

      echo "📄 Copying test.html into azureRepo/"
      cp test.html azureRepo/test.html

      echo "✏️  Committing & pushing if changed..."
      cd azureRepo

      git config user.name  "azure-pipelines"
      git config user.email "builds@dev.azure.com"

      git add test.html
      if git diff --cached --quiet; then
        echo "⚡ No changes to commit."
      else
        git commit -m "🔄 Sync test.html from GitHub @${BUILD_SOURCEVERSION}"
        git push origin main
      fi
    displayName: 'Mirror test.html to Azure DevOps'
    env:
      AZDO_PAT: $(System.AccessToken)
