# azure-pipelines.yml  (now in GitHub/Test)

trigger:
  branches:
    include:
      - main      # or whatever branch you use

pool:
  vmImage: ubuntu-latest

steps:
  # 1) Checkout this GitHub repo (automatically done)
  - checkout: self   

  # 2) Copy test.html into an Azure-managed clone of your private repo
  - script: |
      git clone https://$(AZDO_PAT)@dev.azure.com/zalaris/Zalaris%20IT%20Infrastructure/_git/Zalaris%20IT%20Infra%20-%20Netbox azureRepo
      cp test.html azureRepo/test.html
      cd azureRepo
      git config user.name "azure-pipelines"
      git config user.email "builds@dev.azure.com"
      git add test.html
      if ! git diff --cached --quiet; then
        git commit -m "🔄 Sync test.html from GitHub @$(Build.SourceVersion)"
        git push origin main
      else
        echo "No changes to commit."
      fi
    displayName: 'Mirror test.html to Azure DevOps'
    env:
      AZDO_PAT: $(System.AccessToken)
